import { chromium } from 'playwright';
const browser = await chromium.launch();
const page = await (await browser.newContext({viewport:{width:1440,height:900}})).newPage();
const errs = [];
page.on('pageerror', e => errs.push(e.message.slice(0,90)));
await page.goto('https://mirandafaria.base44.app/pt', { waitUntil:'domcontentloaded', timeout:45000 });
await page.waitForTimeout(6000);
const hero = await page.evaluate(() => {
  const v = document.querySelector('.mf-hero__bg');
  return v ? { src: (v.currentSrc||v.src).split('/').pop(), w: v.videoWidth, ready: v.readyState } : null;
});
console.log('hero:', JSON.stringify(hero));
await page.locator('.mf-nav a:has-text("Sobre")').first().click({timeout:10000});
await page.waitForTimeout(2000);
const about = await page.evaluate(() => document.body.innerText.length);
console.log('navegou p/ Sobre sem reload: len =', about, about>500 ? 'OK' : '*** BRANCO ***');
const r = await page.evaluate(() => { location.hash=''; return document.title });
console.log('title:', r);
console.log('pageerrors:', errs.length?errs:'0');
await browser.close();
